# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: DownloadSecureFile@1
  name: authkey
  displayName: 'Download Service Account Key'
  inputs:
    secureFile: 'GoogleServiceAccountKey.json'
    retryCount: '2'

- script: |
    wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --quiet --usage-reporting=false --path-update=true
    PATH="google-cloud-sdk/bin:${PATH}"
    gcloud --quiet components update
    echo $(authkey.secureFilePath)
  displayName: 'install gcloud SDK'

# - script:
#     gcloud auth activate-service-account --key-file $(authkey.secureFilePath)
#     gcloud functions deploy auto_icone_translator_ftp--region=us-central1 --project=cdot-oim-wzdx-dev
#   displayName: 'deploy icone function'

# - script:
#     gcloud auth activate-service-account --key-file $(authkey.secureFilePath)
#     gcloud functions deploy salesforce-data --runtime--region=us-central1 --project=cdot-oim-wzdx-prod
#   displayName: 'deploy cotrip function'

- script:
    gcloud auth activate-service-account --key-file $(authkey.secureFilePath)
    gcloud functions deploy navjoy-568-translator --region=us-central1 --project=cdot-oim-wzdx-dev
  displayName: 'deploy navjoy function'